services:
  postgres:
    image: ankane/pgvector
    container_name: 'wt-posgres'
    ports:
      - '5555:5432'
    networks:
      - web-travel
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: defaultdb
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

networks:
  web-travel:
    driver: bridge
